name: Libbra

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

    types: [opened, synchronize]

env:
  CI: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Ensure .gradle/caches is empty before writing to it.
      # This helps us stay within Github's cache size limits.
      - name: Clean Cache
        run: rm -rf ~/.gradle/caches

      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Check Dependency Updates
        run: ./gradlew dependencyUpdates -Drevision=release

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

  check-style:
    needs: setup
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Spotless
        run: ./gradlew spotlessCheck

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: reports
          path: app/build/reports

  build:
    needs: check-style
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Create Build Report
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug --scan
          failOnError: true
        id: gradle

      - name: Upload Sample Artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: apk
          path: app/build/outputs/apk/

      - name: Publish Build Report As Comment If Failure
        uses: mshick/add-pr-comment@v1
        if: failure()
        with:
          message: Build failed ${{ steps.gradle.outputs.build-scan-url }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false

  test:
    needs: build
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest :rules:test # lint tests requires this task

  ui-test:
    needs: test
    name: Instrumentation Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      # Restore the cache.
      # Intentionally don't set 'restore-keys' so the cache never contains redundant dependencies.
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }} }}

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            arch: x86_64
            script: ./gradlew connectedDebugAndroidTest
